/* GENERATED by tools/prep-car.mjs from art/hatchback.png, art/van.png, art/pickup.png, art/muralvan.png, art/riotvan.png, art/apc.png —
   do not edit by hand.

   6 vehicles measured off four-view sheets, and where each of those
   24 views ended up in assets/cars/vehicles.png. js/car.js builds boxes
   out of a shape and paints them by projecting that vehicle's views back
   along the axes they were drawn down.

   Every length in `shape` is a fraction of the vehicle's own LENGTH, so
   a model has one scale and `length` sets it. x is +0.5 at the nose and
   -0.5 at the tail, y is half the width to the vehicle's left, z is 0 on
   the ground. */

/** The atlas. One picture for the whole fleet, so a car park full of
    vehicles is one texture and one material. */
export const CAR_ATLAS = { file: 'assets/cars/vehicles.png', w: 512, h: 1031 };

/** The fleet.

    `views` is where each of the four rectangles sits in the atlas, in
    its own pixels, plus the window on the model it covers: `z0` and
    `z1` are the heights its bottom and top edges are at, `half` is how
    far either side of the middle its width reaches. The side view's
    frame IS the model's bounding box, so it only needs the heights; the
    plan view's frame is the length, so it only needs the half width.

    `shape.layers` is the side view's roof line as a stack of boxes,
    lowest first, each as wide as the front view is at that height;
    `runs` is which stretches of the vehicle reach that high. `wheels`
    are the dips in the underside, and sit on the ground — a tracked
    vehicle has none. `roof` is the height every view was anchored on.
    `agree` is how far apart the three views' claims about the width
    were, as a fraction of it: a sheet is over-determined, and this is
    the residual.

    `use` is what keeps a riot van and an APC out of a customer car
    park. */
export const VEHICLES = {
  hatchback: {
    id: 'hatchback', name: 'Hatchback', use: 'civil',
    /* nose to tail, in game units: 3.7 m at 32 units to the metre */
    length: 118,
    views: {
      front: { x: 1, y: 469, w: 117, h: 101, z0: 0.0299, z1: 0.4155, half: 0.2234 },
      rear: { x: 120, y: 469, w: 117, h: 101, z0: 0.0337, z1: 0.4193, half: 0.2234 },
      side: { x: 1, y: 857, w: 223, h: 86, z0: 0, z1: 0.3857 },
      top: { x: 1, y: 669, w: 218, h: 93, half: 0.2133 },
    },
    shape: {
      width: 0.44,
      height: 0.3857,
      sill: 0.0673,
      tyre: 0.0564,
      roof: 0.3812,
      layers: [
        { z0: 0.0673, z1: 0.1525, half: 0.2106, runs: [[-0.5, 0.5]] },
        { z0: 0.1525, z1: 0.1659, half: 0.2069, runs: [[-0.4821, 0.5]] },
        { z0: 0.1659, z1: 0.2332, half: 0.2144, runs: [[-0.4821, 0.4686]] },
        { z0: 0.2332, z1: 0.2601, half: 0.2069, runs: [[-0.4821, 0.37]] },
        { z0: 0.2601, z1: 0.3049, half: 0.2069, runs: [[-0.4821, 0.1861]] },
        { z0: 0.3049, z1: 0.3274, half: 0.2031, runs: [[-0.3969, 0.1861]] },
        { z0: 0.3274, z1: 0.3857, half: 0.173, runs: [[-0.3969, 0.0695]] },
      ],
      wheels: [{ x: 0.3094, r: 0.0706 }, { x: -0.3206, r: 0.0695 }],
      agree: 0.0458,
    },
  },
  van: {
    id: 'van', name: 'Panel van', use: 'civil',
    /* nose to tail, in game units: 5.45 m at 32 units to the metre */
    length: 174,
    views: {
      front: { x: 224, y: 361, w: 102, h: 104, z0: 0.0079, z1: 0.4192, half: 0.2017 },
      rear: { x: 328, y: 361, w: 99, h: 104, z0: 0.0079, z1: 0.4192, half: 0.1957 },
      side: { x: 1, y: 572, w: 231, h: 95, z0: 0, z1: 0.4113 },
      top: { x: 1, y: 764, w: 226, h: 91, half: 0.2013 },
    },
    shape: {
      width: 0.3992,
      height: 0.4113,
      sill: 0.0866,
      tyre: 0.0587,
      roof: 0.4113,
      layers: [
        { z0: 0.0866, z1: 0.1212, half: 0.1937, runs: [[-0.5, 0.5]] },
        { z0: 0.1212, z1: 0.2597, half: 0.1996, runs: [[-0.4957, 0.4913]] },
        { z0: 0.2597, z1: 0.2771, half: 0.1996, runs: [[-0.4221, 0.4913]] },
        { z0: 0.2771, z1: 0.3117, half: 0.1878, runs: [[-0.3442, 0.4913]] },
        { z0: 0.3117, z1: 0.3463, half: 0.18, runs: [[-0.3442, 0.474]] },
        { z0: 0.3463, z1: 0.4113, half: 0.1722, runs: [[-0.2792, 0.474]] },
      ],
      wheels: [{ x: 0.2879, r: 0.0801 }, { x: -0.381, r: 0.0812 }],
      agree: 0.0297,
    },
  },
  pickup: {
    id: 'pickup', name: 'Pickup', use: 'civil',
    /* nose to tail, in game units: 5.2 m at 32 units to the metre */
    length: 166,
    views: {
      front: { x: 107, y: 246, w: 118, h: 108, z0: 0.0027, z1: 0.3962, half: 0.215 },
      rear: { x: 227, y: 246, w: 114, h: 107, z0: 0.0027, z1: 0.3962, half: 0.2096 },
      side: { x: 1, y: 945, w: 216, h: 85, z0: 0, z1: 0.3935 },
      top: { x: 226, y: 857, w: 222, h: 85, half: 0.1914 },
    },
    shape: {
      width: 0.4107,
      height: 0.3935,
      sill: 0.0787,
      tyre: 0.0696,
      roof: 0.3889,
      layers: [
        { z0: 0.0787, z1: 0.2731, half: 0.2054, runs: [[-0.5, 0.5]] },
        { z0: 0.2731, z1: 0.2824, half: 0.1827, runs: [[-0.0648, 0.3148]] },
        { z0: 0.2824, z1: 0.3102, half: 0.1792, runs: [[-0.0648, 0.213]] },
        { z0: 0.3102, z1: 0.338, half: 0.1723, runs: [[-0.0602, 0.213]] },
        { z0: 0.338, z1: 0.3657, half: 0.1653, runs: [[-0.0602, 0.162]] },
        { z0: 0.3657, z1: 0.3935, half: 0.1549, runs: [[-0.0602, 0.1389]] },
      ],
      wheels: [{ x: 0.3426, r: 0.0787 }, { x: -0.2824, r: 0.0787 }],
      agree: 0.1146,
    },
  },
  muralvan: {
    id: 'muralvan', name: 'Custom van', use: 'civil',
    /* nose to tail, in game units: 5.45 m at 32 units to the metre */
    length: 174,
    views: {
      front: { x: 374, y: 125, w: 106, h: 113, z0: -0.0026, z1: 0.4499, half: 0.2122 },
      rear: { x: 1, y: 246, w: 104, h: 113, z0: -0.0026, z1: 0.4499, half: 0.2082 },
      side: { x: 239, y: 469, w: 221, h: 100, z0: 0, z1: 0.4525 },
      top: { x: 234, y: 572, w: 223, h: 95, half: 0.213 },
    },
    shape: {
      width: 0.4223,
      height: 0.4525,
      sill: 0.0588,
      tyre: 0.0996,
      roof: 0.4299,
      layers: [
        { z0: 0.0588, z1: 0.2941, half: 0.2112, runs: [[-0.5, 0.5]] },
        { z0: 0.2941, z1: 0.362, half: 0.1793, runs: [[-0.3824, 0.4819]] },
        { z0: 0.362, z1: 0.4299, half: 0.1633, runs: [[-0.3235, 0.4638]] },
        { z0: 0.4299, z1: 0.4525, half: 0.1275, runs: [[0.3416, 0.414]] },
      ],
      wheels: [{ x: 0.2738, r: 0.0633 }, { x: -0.3552, r: 0.0633 }],
      agree: 0.0226,
    },
  },
  riotvan: {
    id: 'riotvan', name: 'Riot van', use: 'police',
    /* nose to tail, in game units: 5.6 m at 32 units to the metre */
    length: 179,
    views: {
      front: { x: 1, y: 1, w: 106, h: 122, z0: 0.02, z1: 0.4997, half: 0.2084 },
      rear: { x: 109, y: 1, w: 106, h: 122, z0: 0.02, z1: 0.4997, half: 0.2084 },
      side: { x: 1, y: 361, w: 221, h: 106, z0: 0, z1: 0.4796 },
      top: { x: 229, y: 764, w: 209, h: 88, half: 0.2105 },
    },
    shape: {
      width: 0.4182,
      height: 0.4796,
      sill: 0.095,
      tyre: 0.0986,
      roof: 0.4525,
      layers: [
        { z0: 0.095, z1: 0.2443, half: 0.2091, runs: [[-0.5, 0.5]] },
        { z0: 0.2443, z1: 0.3167, half: 0.1854, runs: [[-0.5, 0.4412]] },
        { z0: 0.3167, z1: 0.4027, half: 0.1854, runs: [[-0.4955, 0.2059]] },
        { z0: 0.4027, z1: 0.457, half: 0.1775, runs: [[-0.4955, 0.1335]] },
        { z0: 0.457, z1: 0.4796, half: 0.146, runs: [[0.052, 0.1335]] },
      ],
      wheels: [{ x: 0.2873, r: 0.0928 }, { x: -0.2896, r: 0.0939 }],
      agree: 0.0103,
    },
  },
  apc: {
    id: 'apc', name: 'APC', use: 'military',
    /* nose to tail, in game units: 6.5 m at 32 units to the metre */
    length: 208,
    views: {
      front: { x: 1, y: 125, w: 148, h: 119, z0: 0.0581, z1: 0.4564, half: 0.2477 },
      rear: { x: 217, y: 1, w: 149, h: 119, z0: 0.0581, z1: 0.4564, half: 0.2493 },
      side: { x: 221, y: 669, w: 231, h: 92, z0: 0, z1: 0.3983 },
      top: { x: 151, y: 125, w: 221, h: 115, half: 0.2602 },
    },
    shape: {
      width: 0.5048,
      height: 0.3983,
      sill: 0.0043,
      tyre: 0.0887,
      roof: 0.3593,
      layers: [
        { z0: 0.0043, z1: 0.1039, half: 0.2319, runs: [[-0.5, 0.5]] },
        { z0: 0.1039, z1: 0.1429, half: 0.2524, runs: [[-0.5, 0.487]] },
        { z0: 0.1429, z1: 0.2208, half: 0.2524, runs: [[-0.5, 0.4524]] },
        { z0: 0.2208, z1: 0.2511, half: 0.249, runs: [[-0.5, 0.3485]] },
        { z0: 0.2511, z1: 0.2944, half: 0.2302, runs: [[-0.5, 0.2619]] },
        { z0: 0.2944, z1: 0.3983, half: 0.2149, runs: [[-0.2879, 0.1147]] },
      ],
      wheels: [],
      agree: 0.0496,
    },
  },
};

/** In the order they were measured, and the ones a shopper might own. */
export const VEHICLE_IDS = ["hatchback","van","pickup","muralvan","riotvan","apc"];
export const CIVILIAN = ["hatchback","van","pickup","muralvan"];
