/* GENERATED by tools/prep-car.mjs from art/hatchback.png, art/van.png, art/van2.png, art/pickup.png, art/muralvan.png, art/riotvan.png, art/apc.png —
   do not edit by hand.

   7 vehicles measured off four-view sheets, and where each of those
   28 views ended up in art/vehicles-atlas.png. js/car.js builds boxes
   out of a shape and paints them by projecting that vehicle's views back
   along the axes they were drawn down.

   Every length in `shape` is a fraction of the vehicle's own LENGTH, so
   a model has one scale and `length` sets it. x is +0.5 at the nose and
   -0.5 at the tail, y is half the width to the vehicle's left, z is 0 on
   the ground. */

/** The atlas. One picture for the whole fleet, so a car park full of
    vehicles is one texture and one material. */
export const CAR_ATLAS = { file: 'art/vehicles-atlas.png', w: 512, h: 1140 };

/** The fleet.

    `views` is where each of the four rectangles sits in the atlas, in
    its own pixels, plus the window on the model it covers: `z0` and
    `z1` are the heights its bottom and top edges are at, `half` is how
    far either side of the middle its width reaches. The side view's
    frame IS the model's bounding box, so it only needs the heights; the
    plan view's frame is the length, so it only needs the half width.

    `shape.columns` runs nose to tail — [x, top, half] per column: how
    high the side view's top edge is at that x, and how far either side
    of the middle the plan view reaches there. `shape.levels` runs sill
    to roof — [z, half] per level: how far either side of the middle the
    head-on views reach at that height. A vertex at every column and
    level, at the lower of the two heights and the narrower of the two
    widths, is the body: the visual hull of the three silhouettes.
    `wheels` are the dips in the underside, and sit on the ground — a
    tracked vehicle has none. `roof` is the height every view was anchored on.
    `agree` is how far apart the three views' claims about the width
    were, as a fraction of it: a sheet is over-determined, and this is
    the residual.

    `use` is what keeps a riot van and an APC out of a customer car
    park. */
export const VEHICLES = {
  hatchback: {
    id: 'hatchback', name: 'Hatchback', use: 'civil',
    /* nose to tail, in game units: 3.7 m at 32 units to the metre */
    length: 118,
    views: {
      front: { x: 102, y: 470, w: 117, h: 101, z0: 0.0299, z1: 0.4155, half: 0.2234 },
      rear: { x: 221, y: 470, w: 117, h: 101, z0: 0.0337, z1: 0.4193, half: 0.2234 },
      side: { x: 212, y: 964, w: 223, h: 86, z0: 0, z1: 0.3857 },
      top: { x: 222, y: 775, w: 218, h: 93, half: 0.2133 },
    },
    shape: {
      width: 0.44,
      height: 0.3857,
      sill: 0.0673,
      tyre: 0.0564,
      roof: 0.3812,
      columns: [
        [0.5, 0.1435, 0.0946],
        [0.4865, 0.148, 0.1809],
        [0.4776, 0.1839, 0.1973],
        [0.4552, 0.2152, 0.2017],
        [0.4013, 0.2287, 0.2082],
        [0.3475, 0.2422, 0.2194],
        [0.2803, 0.2511, 0.22],
        [0.222, 0.2601, 0.2129],
        [0.1906, 0.2601, 0.2153],
        [0.1009, 0.3318, 0.2153],
        [0.074, 0.3677, 0.2153],
        [0.0291, 0.3812, 0.2153],
        [-0.0471, 0.3857, 0.2153],
        [-0.1457, 0.3857, 0.2129],
        [-0.2444, 0.3812, 0.2153],
        [-0.3386, 0.3767, 0.22],
        [-0.352, 0.3767, 0.2176],
        [-0.4417, 0.2735, 0.2082],
        [-0.4731, 0.2466, 0.2035],
        [-0.4821, 0.2242, 0.1959],
        [-0.5, 0.148, 0.097],
      ],
      levels: [
        [0.0673, 0.2106],
        [0.1401, 0.2092],
        [0.213, 0.2144],
        [0.2601, 0.2016],
        [0.3027, 0.2069],
        [0.3161, 0.1805],
        [0.3857, 0.1511],
      ],
      wheels: [{ x: 0.3094, r: 0.0706 }, { x: -0.3206, r: 0.0695 }],
      agree: 0.0458,
    },
  },
  van: {
    id: 'van', name: 'Panel van', use: 'civil',
    /* nose to tail, in game units: 5.45 m at 32 units to the metre */
    length: 174,
    views: {
      front: { x: 340, y: 361, w: 102, h: 104, z0: 0.0079, z1: 0.4192, half: 0.2017 },
      rear: { x: 1, y: 470, w: 99, h: 104, z0: 0.0079, z1: 0.4192, half: 0.1957 },
      side: { x: 1, y: 678, w: 231, h: 95, z0: 0, z1: 0.4113 },
      top: { x: 234, y: 870, w: 226, h: 91, half: 0.2013 },
    },
    shape: {
      width: 0.3992,
      height: 0.4113,
      sill: 0.0866,
      tyre: 0.0587,
      roof: 0.4113,
      columns: [
        [0.5, 0.1212, 0.1053],
        [0.487, 0.2338, 0.1796],
        [0.4437, 0.2597, 0.1886],
        [0.4091, 0.2641, 0.1974],
        [0.3485, 0.2944, 0.1974],
        [0.3268, 0.2944, 0.1974],
        [0.2749, 0.355, 0.193],
        [0.2619, 0.3896, 0.193],
        [0.2403, 0.4026, 0.193],
        [0.2229, 0.4026, 0.193],
        [0.2143, 0.4026, 0.182],
        [0.1407, 0.4069, 0.182],
        [0.132, 0.4113, 0.1952],
        [0.0455, 0.4113, 0.1952],
        [-0.0411, 0.4113, 0.1974],
        [-0.1277, 0.4113, 0.193],
        [-0.2143, 0.4113, 0.1952],
        [-0.3009, 0.4113, 0.1996],
        [-0.3961, 0.4113, 0.1908],
        [-0.4567, 0.3983, 0.1886],
        [-0.487, 0.2684, 0.1798],
        [-0.5, 0.1212, 0.0855],
      ],
      levels: [
        [0.0866, 0.1955],
        [0.1786, 0.1955],
        [0.2706, 0.1996],
        [0.2792, 0.1875],
        [0.3387, 0.1754],
        [0.3983, 0.1624],
        [0.4113, 0.1401],
      ],
      wheels: [{ x: -0.2879, r: 0.0801 }, { x: 0.381, r: 0.0812 }],
      agree: 0.0297,
    },
  },
  van2: {
    id: 'van2', name: 'Work van', use: 'civil',
    /* nose to tail, in game units: 5.45 m at 32 units to the metre */
    length: 174,
    views: {
      front: { x: 107, y: 246, w: 106, h: 109, z0: 0.0123, z1: 0.4598, half: 0.2176 },
      rear: { x: 215, y: 246, w: 106, h: 109, z0: 0.0123, z1: 0.4598, half: 0.2176 },
      side: { x: 224, y: 576, w: 219, h: 98, z0: 0, z1: 0.4475 },
      top: { x: 1, y: 775, w: 219, h: 93, half: 0.2123 },
    },
    shape: {
      width: 0.4317,
      height: 0.4475,
      sill: 0.0913,
      tyre: 0.0774,
      roof: 0.4475,
      columns: [
        [0.5, 0.1324, 0.0812],
        [0.4817, 0.2557, 0.1961],
        [0.468, 0.2694, 0.2042],
        [0.3858, 0.2877, 0.2135],
        [0.363, 0.2968, 0.2158],
        [0.3037, 0.3196, 0.2135],
        [0.258, 0.3699, 0.2089],
        [0.2443, 0.4064, 0.2089],
        [0.2215, 0.4338, 0.2089],
        [0.1986, 0.4384, 0.2089],
        [0.1804, 0.4384, 0.1949],
        [0.1164, 0.4475, 0.1949],
        [0.1073, 0.4475, 0.1949],
        [0.0982, 0.4475, 0.2112],
        [0.0068, 0.4475, 0.2089],
        [-0.0845, 0.4475, 0.2089],
        [-0.1758, 0.4475, 0.2089],
        [-0.2671, 0.4475, 0.2158],
        [-0.3584, 0.4475, 0.2135],
        [-0.3676, 0.4475, 0.2089],
        [-0.4452, 0.4338, 0.2007],
        [-0.4863, 0.2831, 0.1973],
        [-0.5, 0.1324, 0.123],
      ],
      levels: [
        [0.0913, 0.2158],
        [0.145, 0.2158],
        [0.1986, 0.2158],
        [0.2683, 0.2077],
        [0.3333, 0.1995],
        [0.4315, 0.1751],
        [0.4475, 0.1537],
      ],
      wheels: [{ x: 0.3653, r: 0.0856 }, { x: -0.2968, r: 0.0856 }],
      agree: 0.0244,
    },
  },
  pickup: {
    id: 'pickup', name: 'Pickup', use: 'civil',
    /* nose to tail, in game units: 5.2 m at 32 units to the metre */
    length: 166,
    views: {
      front: { x: 323, y: 246, w: 118, h: 108, z0: 0.0027, z1: 0.3962, half: 0.215 },
      rear: { x: 1, y: 361, w: 114, h: 107, z0: 0.0027, z1: 0.3962, half: 0.2096 },
      side: { x: 225, y: 1054, w: 216, h: 85, z0: 0, z1: 0.3935 },
      top: { x: 1, y: 1054, w: 222, h: 85, half: 0.1914 },
    },
    shape: {
      width: 0.4107,
      height: 0.3935,
      sill: 0.0787,
      tyre: 0.0696,
      roof: 0.3889,
      columns: [
        [0.5, 0.2222, 0.0604],
        [0.4815, 0.25, 0.1837],
        [0.4676, 0.2546, 0.1949],
        [0.3796, 0.2639, 0.2029],
        [0.3148, 0.2731, 0.2029],
        [0.2407, 0.2731, 0.2005],
        [0.2176, 0.2824, 0.2025],
        [0.1296, 0.3843, 0.2029],
        [0.0926, 0.3935, 0.2029],
        [0.0185, 0.3935, 0.2029],
        [-0.0509, 0.3889, 0.2029],
        [-0.0694, 0.2685, 0.2029],
        [-0.1389, 0.2685, 0.2029],
        [-0.2083, 0.2685, 0.2029],
        [-0.2824, 0.2685, 0.2054],
        [-0.375, 0.2731, 0.2005],
        [-0.4676, 0.2731, 0.1957],
        [-0.5, 0.2269, 0.1788],
      ],
      levels: [
        [0.0787, 0.2001],
        [0.1331, 0.2019],
        [0.1875, 0.2054],
        [0.2569, 0.1945],
        [0.3183, 0.1729],
        [0.3796, 0.1513],
        [0.3935, 0.1012],
      ],
      wheels: [{ x: 0.3426, r: 0.0787 }, { x: -0.2824, r: 0.0787 }],
      agree: 0.1146,
    },
  },
  muralvan: {
    id: 'muralvan', name: 'Custom van', use: 'civil',
    /* nose to tail, in game units: 5.45 m at 32 units to the metre */
    length: 174,
    views: {
      front: { x: 374, y: 125, w: 106, h: 113, z0: -0.0026, z1: 0.4499, half: 0.2122 },
      rear: { x: 1, y: 246, w: 104, h: 113, z0: -0.0026, z1: 0.4499, half: 0.2082 },
      side: { x: 1, y: 576, w: 221, h: 100, z0: 0, z1: 0.4525 },
      top: { x: 234, y: 678, w: 223, h: 95, half: 0.213 },
    },
    shape: {
      width: 0.4223,
      height: 0.4525,
      sill: 0.0588,
      tyre: 0.0996,
      roof: 0.4299,
      columns: [
        [0.5, 0.2127, 0.0867],
        [0.4819, 0.2489, 0.1019],
        [0.4729, 0.2489, 0.1566],
        [0.4593, 0.2579, 0.1795],
        [0.405, 0.2896, 0.1935],
        [0.3869, 0.2941, 0.2023],
        [0.3326, 0.3937, 0.2067],
        [0.3235, 0.4027, 0.2067],
        [0.2511, 0.4208, 0.2067],
        [0.2421, 0.4208, 0.1956],
        [0.2149, 0.4253, 0.1956],
        [0.138, 0.4253, 0.1956],
        [0.0566, 0.4299, 0.1956],
        [-0.0249, 0.4299, 0.1956],
        [-0.1063, 0.4299, 0.1956],
        [-0.1878, 0.4299, 0.1956],
        [-0.2104, 0.4299, 0.2088],
        [-0.2692, 0.4299, 0.2112],
        [-0.3371, 0.4299, 0.2085],
        [-0.3552, 0.448, 0.2048],
        [-0.3643, 0.4525, 0.1911],
        [-0.414, 0.4525, 0.1911],
        [-0.4231, 0.4253, 0.1911],
        [-0.4367, 0.4253, 0.1911],
        [-0.4502, 0.4163, 0.1867],
        [-0.4593, 0.3982, 0.18],
        [-0.4819, 0.3937, 0.1756],
        [-0.491, 0.3665, 0.1702],
        [-0.5, 0.3303, 0.0422],
      ],
      levels: [
        [0.0588, 0.2112],
        [0.1516, 0.2111],
        [0.1652, 0.1992],
        [0.2557, 0.2012],
        [0.2783, 0.1834],
        [0.3371, 0.1726],
        [0.3959, 0.1583],
        [0.4389, 0.1233],
        [0.4525, 0.0568],
      ],
      wheels: [{ x: -0.2738, r: 0.0633 }, { x: 0.3552, r: 0.0633 }],
      agree: 0.0226,
    },
  },
  riotvan: {
    id: 'riotvan', name: 'Riot van', use: 'police',
    /* nose to tail, in game units: 5.6 m at 32 units to the metre */
    length: 179,
    views: {
      front: { x: 1, y: 1, w: 106, h: 122, z0: 0.02, z1: 0.4997, half: 0.2084 },
      rear: { x: 109, y: 1, w: 106, h: 122, z0: 0.02, z1: 0.4997, half: 0.2084 },
      side: { x: 117, y: 361, w: 221, h: 106, z0: 0, z1: 0.4796 },
      top: { x: 1, y: 964, w: 209, h: 88, half: 0.2105 },
    },
    shape: {
      width: 0.4182,
      height: 0.4796,
      sill: 0.095,
      tyre: 0.0986,
      roof: 0.4525,
      columns: [
        [0.5, 0.1719, 0.0832],
        [0.4819, 0.2443, 0.0876],
        [0.4638, 0.2443, 0.1259],
        [0.4412, 0.267, 0.1259],
        [0.4186, 0.2941, 0.1665],
        [0.3914, 0.2986, 0.1972],
        [0.3643, 0.3032, 0.2064],
        [0.2692, 0.3167, 0.2067],
        [0.2104, 0.3167, 0.2066],
        [0.138, 0.4027, 0.2043],
        [0.1244, 0.4208, 0.1925],
        [0.0973, 0.4434, 0.1972],
        [0.0747, 0.4796, 0.1925],
        [-0.0023, 0.4796, 0.2067],
        [-0.0249, 0.4796, 0.1925],
        [-0.0566, 0.4525, 0.1925],
        [-0.1335, 0.457, 0.1925],
        [-0.1425, 0.457, 0.202],
        [-0.224, 0.457, 0.2067],
        [-0.3009, 0.4525, 0.2091],
        [-0.3778, 0.4525, 0.2067],
        [-0.4457, 0.4525, 0.1877],
        [-0.4864, 0.448, 0.1877],
        [-0.5, 0.4344, 0.1663],
      ],
      levels: [
        [0.095, 0.2091],
        [0.164, 0.2091],
        [0.233, 0.2012],
        [0.2466, 0.1854],
        [0.3348, 0.1854],
        [0.4231, 0.1775],
        [0.4367, 0.1708],
        [0.4661, 0.1499],
        [0.4796, 0.1223],
      ],
      wheels: [{ x: 0.2873, r: 0.0928 }, { x: -0.2896, r: 0.0939 }],
      agree: 0.0103,
    },
  },
  apc: {
    id: 'apc', name: 'APC', use: 'military',
    /* nose to tail, in game units: 6.5 m at 32 units to the metre */
    length: 208,
    views: {
      front: { x: 1, y: 125, w: 148, h: 119, z0: 0.0581, z1: 0.4564, half: 0.2477 },
      rear: { x: 217, y: 1, w: 149, h: 119, z0: 0.0581, z1: 0.4564, half: 0.2493 },
      side: { x: 1, y: 870, w: 231, h: 92, z0: 0, z1: 0.3983 },
      top: { x: 151, y: 125, w: 221, h: 115, half: 0.2602 },
    },
    shape: {
      width: 0.5048,
      height: 0.3983,
      sill: 0,
      tyre: 0.0887,
      roof: 0.3593,
      columns: [
        [0.5, 0.0823, 0.0812],
        [0.487, 0.1429, 0.128],
        [0.4784, 0.1429, 0.1762],
        [0.4654, 0.1429, 0.1778],
        [0.4524, 0.1861, 0.1778],
        [0.4307, 0.1948, 0.1778],
        [0.4177, 0.1991, 0.2392],
        [0.3745, 0.2165, 0.2524],
        [0.3182, 0.2338, 0.2524],
        [0.2662, 0.2511, 0.2524],
        [0.2489, 0.2771, 0.2524],
        [0.197, 0.2857, 0.2524],
        [0.119, 0.342, 0.2524],
        [0.0325, 0.3506, 0.2524],
        [-0.0541, 0.3636, 0.2524],
        [-0.0671, 0.3723, 0.2524],
        [-0.0931, 0.3983, 0.2524],
        [-0.1234, 0.381, 0.2524],
        [-0.1364, 0.381, 0.2458],
        [-0.1883, 0.381, 0.2502],
        [-0.2056, 0.3636, 0.2524],
        [-0.2879, 0.3636, 0.2524],
        [-0.3095, 0.2944, 0.2524],
        [-0.3831, 0.29, 0.2524],
        [-0.4567, 0.2857, 0.2524],
        [-0.474, 0.2771, 0.2524],
        [-0.4913, 0.2554, 0.2489],
        [-0.5, 0.2554, 0.1887],
      ],
      levels: [
        [0, 0.2251],
        [0.066, 0.2319],
        [0.132, 0.2319],
        [0.1407, 0.2524],
        [0.2143, 0.2521],
        [0.276, 0.2251],
        [0.3377, 0.1958],
        [0.3615, 0.1228],
        [0.3983, 0.1189],
      ],
      wheels: [],
      agree: 0.0496,
    },
  },
};

/** In the order they were measured, and the ones a shopper might own. */
export const VEHICLE_IDS = ["hatchback","van","van2","pickup","muralvan","riotvan","apc"];
export const CIVILIAN = ["hatchback","van","van2","pickup","muralvan"];
