/* GENERATED by tools/prep-car.mjs from art/riotvan.png — do not edit by hand.

   A vehicle measured off a four-view sheet, and where each of those
   views ended up in assets/cars/riotvan.png. js/car.js builds boxes out of
   the shape and paints them by projecting the views back along the axes
   they were drawn down.

   Lengths are fractions of the vehicle's own LENGTH, so the model has
   one scale and js/car.js sets it. x is +0.5 at the nose and -0.5 at the
   tail, y is +0.2091 to the vehicle's left, z is 0 on the ground. */

/** The atlas, and where the four views sit in it, in its own pixels —
    plus the window on the model each of those rectangles covers: `z0`
    and `z1` are the heights its bottom and top edges are at, `half` is
    how far either side of the middle its width reaches. The side view's
    frame IS the model's bounding box, so it only needs the heights; the
    plan view's frame is the length, so it only needs the half width. */
export const CAR_ATLAS = { file: 'assets/cars/riotvan.png', w: 256, h: 322 };
export const CAR_VIEWS = {
  front: { x: 1, y: 1, w: 106, h: 122, z0: 0.0273, z1: 0.5069, half: 0.2084 },
  rear: { x: 109, y: 1, w: 106, h: 122, z0: 0.0273, z1: 0.5069, half: 0.2084 },
  side: { x: 1, y: 125, w: 221, h: 106, z0: 0, z1: 0.4796 },
  top: { x: 1, y: 233, w: 209, h: 88, half: 0.2105 },
};

/** The vehicle. `layers` is the side view's roof line as a stack of
    boxes, lowest first, each as wide as the front view is at that
    height; `runs` is which stretches of the vehicle reach that high.
    `wheels` are the two dips in the underside, and sit on the ground. */
export const CAR_SHAPE = {
  width: 0.4182,
  height: 0.4796,
  sill: 0.095,
  tyre: 0.0986,
  /** The roof line: the height every view was anchored on, so the top of
      the body and the top of each view's window agree about where it is. */
  roof: 0.448,
  layers: [
    { z0: 0.095, z1: 0.2443, half: 0.2091, runs: [[-0.5, 0.5]] },
    { z0: 0.2443, z1: 0.3167, half: 0.1973, runs: [[-0.5, 0.4412]] },
    { z0: 0.3167, z1: 0.4027, half: 0.1854, runs: [[-0.4955, 0.2059]] },
    { z0: 0.4027, z1: 0.457, half: 0.1815, runs: [[-0.4955, 0.1335]] },
    { z0: 0.457, z1: 0.4796, half: 0.146, runs: [[0.052, 0.1335]] },
  ],
  wheels: [
    { x: 0.2873, r: 0.0928 },
    { x: -0.2896, r: 0.0939 },
  ],
  /** How far apart the three views' claims about the width were, as a
      fraction of it. The sheet is over-determined; this is the residual. */
  agree: 0.0103,
};
